################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../accel.c \
../app.c \
../application_properties.c \
../ble.c \
../gatt_db.c \
../gecko_ble_errors.c \
../gpio.c \
../i2c.c \
../init_app.c \
../init_board.c \
../init_mcu.c \
../irq.c \
../log.c \
../main.c \
../oscillators.c \
../scheduler.c \
../timer.c 

OBJS += \
./accel.o \
./app.o \
./application_properties.o \
./ble.o \
./gatt_db.o \
./gecko_ble_errors.o \
./gpio.o \
./i2c.o \
./init_app.o \
./init_board.o \
./init_mcu.o \
./irq.o \
./log.o \
./main.o \
./oscillators.o \
./scheduler.o \
./timer.o 

C_DEPS += \
./accel.d \
./app.d \
./application_properties.d \
./ble.d \
./gatt_db.d \
./gecko_ble_errors.d \
./gpio.d \
./i2c.d \
./init_app.d \
./init_board.d \
./init_mcu.d \
./irq.d \
./log.d \
./main.d \
./oscillators.d \
./scheduler.d \
./timer.d 


# Each subdirectory must supply rules for building sources it contributes
accel.o: ../accel.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-DEFR32BG13P732F512GM48=1' -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\halconfig" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\CMSIS\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\drivers" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\bsp" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\halconfig\inc\hal-config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\app\bluetooth\common\util" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\uartdrv\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ble" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader\api" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"accel.d" -MT"accel.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

app.o: ../app.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-DEFR32BG13P732F512GM48=1' -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\halconfig" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\CMSIS\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\drivers" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\bsp" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\halconfig\inc\hal-config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\app\bluetooth\common\util" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\uartdrv\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ble" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader\api" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"app.d" -MT"app.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

application_properties.o: ../application_properties.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-DEFR32BG13P732F512GM48=1' -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\halconfig" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\CMSIS\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\drivers" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\bsp" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\halconfig\inc\hal-config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\app\bluetooth\common\util" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\uartdrv\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ble" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader\api" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"application_properties.d" -MT"application_properties.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

ble.o: ../ble.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-DEFR32BG13P732F512GM48=1' -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\halconfig" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\CMSIS\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\drivers" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\bsp" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\halconfig\inc\hal-config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\app\bluetooth\common\util" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\uartdrv\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ble" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader\api" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"ble.d" -MT"ble.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gatt_db.o: ../gatt_db.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-DEFR32BG13P732F512GM48=1' -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\halconfig" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\CMSIS\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\drivers" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\bsp" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\halconfig\inc\hal-config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\app\bluetooth\common\util" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\uartdrv\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ble" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader\api" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"gatt_db.d" -MT"gatt_db.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_ble_errors.o: ../gecko_ble_errors.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-DEFR32BG13P732F512GM48=1' -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\halconfig" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\CMSIS\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\drivers" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\bsp" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\halconfig\inc\hal-config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\app\bluetooth\common\util" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\uartdrv\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ble" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader\api" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"gecko_ble_errors.d" -MT"gecko_ble_errors.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gpio.o: ../gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-DEFR32BG13P732F512GM48=1' -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\halconfig" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\CMSIS\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\drivers" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\bsp" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\halconfig\inc\hal-config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\app\bluetooth\common\util" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\uartdrv\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ble" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader\api" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"gpio.d" -MT"gpio.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

i2c.o: ../i2c.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-DEFR32BG13P732F512GM48=1' -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\halconfig" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\CMSIS\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\drivers" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\bsp" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\halconfig\inc\hal-config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\app\bluetooth\common\util" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\uartdrv\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ble" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader\api" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"i2c.d" -MT"i2c.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

init_app.o: ../init_app.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-DEFR32BG13P732F512GM48=1' -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\halconfig" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\CMSIS\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\drivers" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\bsp" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\halconfig\inc\hal-config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\app\bluetooth\common\util" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\uartdrv\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ble" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader\api" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"init_app.d" -MT"init_app.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

init_board.o: ../init_board.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-DEFR32BG13P732F512GM48=1' -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\halconfig" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\CMSIS\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\drivers" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\bsp" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\halconfig\inc\hal-config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\app\bluetooth\common\util" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\uartdrv\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ble" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader\api" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"init_board.d" -MT"init_board.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

init_mcu.o: ../init_mcu.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-DEFR32BG13P732F512GM48=1' -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\halconfig" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\CMSIS\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\drivers" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\bsp" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\halconfig\inc\hal-config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\app\bluetooth\common\util" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\uartdrv\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ble" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader\api" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"init_mcu.d" -MT"init_mcu.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

irq.o: ../irq.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-DEFR32BG13P732F512GM48=1' -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\halconfig" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\CMSIS\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\drivers" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\bsp" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\halconfig\inc\hal-config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\app\bluetooth\common\util" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\uartdrv\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ble" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader\api" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"irq.d" -MT"irq.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

log.o: ../log.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-DEFR32BG13P732F512GM48=1' -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\halconfig" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\CMSIS\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\drivers" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\bsp" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\halconfig\inc\hal-config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\app\bluetooth\common\util" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\uartdrv\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ble" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader\api" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"log.d" -MT"log.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

main.o: ../main.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-DEFR32BG13P732F512GM48=1' -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\halconfig" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\CMSIS\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\drivers" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\bsp" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\halconfig\inc\hal-config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\app\bluetooth\common\util" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\uartdrv\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ble" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader\api" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"main.d" -MT"main.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

oscillators.o: ../oscillators.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-DEFR32BG13P732F512GM48=1' -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\halconfig" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\CMSIS\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\drivers" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\bsp" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\halconfig\inc\hal-config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\app\bluetooth\common\util" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\uartdrv\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ble" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader\api" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"oscillators.d" -MT"oscillators.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

scheduler.o: ../scheduler.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-DEFR32BG13P732F512GM48=1' -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\halconfig" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\CMSIS\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\drivers" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\bsp" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\halconfig\inc\hal-config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\app\bluetooth\common\util" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\uartdrv\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ble" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader\api" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"scheduler.d" -MT"scheduler.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

timer.o: ../timer.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DHAL_CONFIG=1' '-D__StackLimit=0x20000000' '-DEFR32BG13P732F512GM48=1' -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\halconfig" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emlib\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\CMSIS\Include" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\drivers" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\hardware\kit\common\bsp" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\common" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\halconfig\inc\hal-config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\app\bluetooth\common\util" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\uartdrv\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\common\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\protocol\bluetooth\ble_stack\inc\soc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\chip\efr32\efr32xg1x" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ble" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\Device\SiliconLabs\EFR32BG13P\Source\GCC" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\service\sleeptimer\config" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader\api" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\radio\rail_lib\protocol\ieee802154" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\emdrv\sleep\src" -I"C:\Users\bryan\SimplicityStudio\v4_workspace\soc-empty\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"timer.d" -MT"timer.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


